<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Adding_and_removing_elements.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4])
a2 = np.append(a,6)
print(a2)

[1 2 3 4 6]


In [3]:
a = np.array([[1,2],[3,4]])
a2 = np.append(a,6)
print(a2) # even though it 2D it converts into 1D

[1 2 3 4 6]


In [4]:
a = np.array([1,2,3,4])
a2 = np.insert(a,1,6)
print(a2)

[1 6 2 3 4]


In [5]:
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,1,6)
print(a2)

[1 6 2 3 4]


In [6]:
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,1,[6,7])
print(a2)

[1 6 7 2 3 4]


In [9]:
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,1,[6,7] , axis =1)
print(a2)
print("__________________________")
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,1,[6,7] , axis =0)
print(a2)

[[1 6 2]
 [3 7 4]]
__________________________
[[1 2]
 [6 7]
 [3 4]]


In [10]:
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,1,[6] , axis =1) # even though we give one value it fills both
print(a2)
print("__________________________")
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,1,[6] , axis =0)# even though we give one value it fills both
print(a2)

[[1 6 2]
 [3 6 4]]
__________________________
[[1 2]
 [6 6]
 [3 4]]


In [11]:
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,[1,2],[6,7] , axis =1)
print(a2)
#The key is that when you specify multiple insertion positions [1,2], the second position (2) is counted based on the array's state after the first insertion
print("__________________________")
a = np.array([[1,2],[3,4]])
a2 = np.insert(a,[1,2],[6,7] , axis =0)
print(a2)

[[1 6 2 7]
 [3 6 4 7]]
__________________________
[[1 2]
 [6 7]
 [3 4]
 [6 7]]


In [14]:
#1D
a = np.array([1,2,3,4])
a2 = np.delete(a,3) #3 is index not element
print(a2)

[1 2 3]


In [15]:
a = np.array([1,2,3,4])
a2 = np.delete(a,[0,3])
print(a2)

[2 3]


In [18]:
#2D delete
a = np.array([[1,2],[3,4]])
a2 = np.delete(a,1, axis =0) # axis= 0 row wise
print(a2)
print()
#2D delete
a = np.array([[1,2],[3,4]])
a2 = np.delete(a,1, axis =1) #axis= 1 column wise
print(a2)

[[1 2]]

[[1]
 [3]]
