<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Aggregating_Functions_in_arrays_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [10]:
a = np.array([10,20,30,40])

print(np.sum(a))
print(np.prod(a))
print(np.min(a))
print(np.max(a))
print(np.size(a)) #in numpy we dont have count we use size
print(np.mean(a))
print(np.cumsum(a)) #10, 10+20,10+20+30,....
print(np.cumprod(a))

100
240000
10
40
4
25.0
[ 10  30  60 100]
[    10    200   6000 240000]


In [13]:
# For 2D arrays, you can specify axis
arr_2d = np.array([[1, 2, 3],
                              [4, 5, 6]])
print(np.sum(arr_2d, axis=0) ) # Sum each column: [5, 7, 9]
print()
print()

print(np.sum(arr_2d, axis=1))  # Sum each row: [6, 15]


[5 7 9]


[ 6 15]
