<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Concatenate_Split_Stack.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [3]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
a3 = np.concatenate([a1,a2])
print(a3)

[1 2 3 4 5 6]


In [7]:
#For 2D array
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,7]])
a3 = np.concatenate([a1,a2]) # here axis= 0 combine vertically
print(a3)  # [[1 2], [3 4], [4,5], [6,7]]

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [8]:
#For 2D array
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,7]])
a3 = np.concatenate([a1,a2],axis=1) # here axis=1 combine Horizantally
print(a3)  # [[1 2 4, 5], [3 4 6 7]]

[[1 2 4 5]
 [3 4 6 7]]


In [9]:
#For 2D array
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,7]])
a3 = np.vstack([a1,a2]) #same as concatenate axis =0
print(a3)

[[1 2]
 [3 4]
 [4 5]
 [6 7]]


In [10]:
#For 2D array
a1 = np.array([[1,2],[3,4]])
a2 = np.array([[4,5],[6,7]])
a3 = np.hstack([a1,a2]) #same as concatenate axis = 1
print(a3)

[[1 2 4 5]
 [3 4 6 7]]


In [12]:
a1 = np.array([1,2,3])
a2 = np.array([4,5,6])
columnstackarray = np.column_stack([a1,a2])
print(columnstackarray)

[[1 4]
 [2 5]
 [3 6]]


In [15]:
a1 = np.array([1,2,3,4,5,6])
a2= np.split(a1,3)
print(a2)

[array([1, 2]), array([3, 4]), array([5, 6])]


In [17]:
#split at specific indices
a1 = np.array([1,2,3,4,5,6])
a2= np.split(a1,[2,4])
print(a2)


[array([1, 2]), array([3, 4]), array([5, 6])]


In [18]:
a = np.array([[1,2,3,4],[5,6,7,8]])
hsplit = np.hsplit(a,2)
vsplit = np.vsplit(a,2)
print(hsplit)
print(vsplit)

[array([[1, 2],
       [5, 6]]), array([[3, 4],
       [7, 8]])]
[array([[1, 2, 3, 4]]), array([[5, 6, 7, 8]])]
