<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Indexing and Slicing**

##**Indexing**

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [2]:
import numpy as np
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [3]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])
#index rows and columns start from 0 1 2 ....

3


In [4]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

##**Slicing**

In [5]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [7]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [9]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning
a
# 1st b=0,1,2,3,4
# b[::-1] is reverse = 4,3,2,1,0
#reversing and then assigning that value from 5th index of a
#a[5:] = 0,1,2,3,4,4,3,2,1,0

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

#**Copies and Views**

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

When modifying the view, the original array is modified as well:

In [10]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [12]:
np.shares_memory(a, b)

True

In [13]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [14]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [15]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
#wen we use copy function it doesnt shares memory and value wont get updated in a unlike aboe example
c

array([0, 2, 4, 6, 8])

In [16]:
np.shares_memory(a, c)

False

In [18]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#**Fancy Indexing**

NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views.

Using Boolean Mask

In [19]:
a = np.random.randint(0, 20, 15)
a

array([18,  0,  4,  3, 10, 10, 17, 11,  9,  2, 14, 18, 19,  8,  3])

In [20]:
mask = (a % 2 == 0)

In [21]:
otp = a[mask]
otp

array([18,  0,  4, 10, 10,  2, 14, 18,  8])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [22]:
a[mask] = -1
a
#all the even numbers become -1

array([-1, -1, -1,  3, -1, -1, 17, 11,  9, -1, -1, -1, 19, -1,  3])

**Indexing with an array of integers**

In [23]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [24]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [25]:
# New values can be assigned
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])