<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Indexing_and_Slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**Indexing and Slicing**

In [1]:
import numpy as np
arr =np.array([[1,2,3,4],[5,6,7,8],[2,6,7,9]])
print(arr)

[[1 2 3 4]
 [5 6 7 8]
 [2 6 7 9]]


In [2]:
#if u want  to access 1st row
arr[0]

array([1, 2, 3, 4])

In [7]:
#if u want  to access 1st column
arr[:,0]

array([1, 5, 2])

In [10]:
print(arr[0:])
print(arr[:0])


[[1 2 3 4]
 [5 6 7 8]
 [2 6 7 9]]
[]


In [14]:
arr =np.array([[1,2,3,4],[5,6,7,8],[2,6,7,9]])
print(arr)
print(arr[0][0]) #1st row 1st element
print(arr[1][2]) # 2nd row 3rd element


[[1 2 3 4]
 [5 6 7 8]
 [2 6 7 9]]
1
7


In [17]:
arr =np.array([[1,2,3,4],[5,6,7,8],[2,6,7,9]])
print(arr)
arr[1:,1:] #wen i want elements only 678 in 2nd row and 679 in 3rd row

[[1 2 3 4]
 [5 6 7 8]
 [2 6 7 9]]


array([[6, 7, 8],
       [6, 7, 9]])

In [29]:
arr =np.array([[1,2,3,4],[5,6,7,8],[1,5,2,9]])
print(arr)
print()
print(arr[0:2])
print()
print(arr[0:2,1:3]) #if i want to access 2,3,6,7, only


[[1 2 3 4]
 [5 6 7 8]
 [1 5 2 9]]

[[1 2 3 4]
 [5 6 7 8]]

[[2 3]
 [6 7]]


In [31]:
arr =np.array([[1,2,3,4],[5,6,7,8],[1,5,2,9],[0,3,7,2]])
print(arr)
print()
print()
print(arr[1:3,1:3])


[[1 2 3 4]
 [5 6 7 8]
 [1 5 2 9]
 [0 3 7 2]]


[[6 7]
 [5 2]]


In [42]:
# Modifying array
arr =np.arange(12).reshape(3,4)
print(arr)

print()
print()

arr[0,0]=100
print(arr)

print()
print()

arr[0:]=100
print(arr)
print()
print()
arr =np.arange(12).reshape(3,4)
print(arr)
print()
print()
arr[1:]=100
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]


[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


[[  0   1   2   3]
 [100 100 100 100]
 [100 100 100 100]]


##**Indexing**

The items of an array can be accessed and assigned to the same way as other Python sequences (e.g. lists):

In [ ]:
import numpy as np
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [ ]:
# For multidimensional arrays, indexes are tuples of integers:

a = np.diag([1, 2, 3])

print(a[2, 2])
#index rows and columns start from 0 1 2 ....

3


In [ ]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

##**Slicing**

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [ ]:
#we can also combine assignment and slicing:
a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [ ]:
b = np.arange(5)
a[5:] = b[::-1]  #assigning
a
# 1st b=0,1,2,3,4
# b[::-1] is reverse = 4,3,2,1,0
#reversing and then assigning that value from 5th index of a
#a[5:] = 0,1,2,3,4,4,3,2,1,0

array([0, 1, 2, 3, 4, 4, 3, 2, 1, 0])

#**Copies and Views**

A slicing operation creates a view on the original array, which is just a way of accessing array data. Thus the original array is not copied in memory. You can use np.may_share_memory() to check if two arrays share the same memory block.

When modifying the view, the original array is modified as well:

In [ ]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, b)

True

In [ ]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [ ]:
a  #eventhough we modified b,  it updated 'a' because both shares same memory

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [ ]:
a = np.arange(10)
c = a[::2].copy()     #force a copy
#wen we use copy function it doesnt shares memory and value wont get updated in a unlike aboe example
c

array([0, 2, 4, 6, 8])

In [ ]:
np.shares_memory(a, c)

False

In [ ]:
c[0] = 10
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

#**Fancy Indexing**

NumPy arrays can be indexed with slices, but also with boolean or integer arrays (masks). This method is called fancy indexing. It creates copies not views.

Using Boolean Mask

In [ ]:
a = np.random.randint(0, 20, 15)
a

array([18,  0,  4,  3, 10, 10, 17, 11,  9,  2, 14, 18, 19,  8,  3])

In [ ]:
mask = (a % 2 == 0)

In [ ]:
otp = a[mask]
otp

array([18,  0,  4, 10, 10,  2, 14, 18,  8])

**Indexing with a mask can be very useful to assign a new value to a sub-array:**

In [ ]:
a[mask] = -1
a
#all the even numbers become -1

array([-1, -1, -1,  3, -1, -1, 17, 11,  9, -1, -1, -1, 19, -1,  3])

**Indexing with an array of integers**

In [ ]:
a = np.arange(0, 100, 10)
a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
#Indexing can be done with an array of integers, where the same index is repeated several time:
a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [ ]:
# New values can be assigned
a[[9, 7]] = -200
a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])