<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Introduction_and_functions_to_create_arrays_in_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

* Python library used for working with arrays.
* NumPy stands for Numerical Python.
* NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.

In [1]:
import numpy as np
a = np.array([1,2,3,4])
print(a)
print(np.arange(20))

[1 2 3 4]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


**%timeit -  find the execution time of small bits of Python code.**

In [5]:
#Using Python Lists
list1=range(1000)
%timeit [i**2 for i in list1]
#using 432 micro seconds
#1 micro sec is 1 millionth of a second
#1 million microsec = 1 sec

432 µs ± 105 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
#using NumPy
a = np.arange(1000)
%timeit a**2

1.38 µs ± 301 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


#**Creating NumPy arrays**

###**1D Array**

In [7]:
#1D Array
a = np.array([1,2,3,4,5])
a

array([1, 2, 3, 4, 5])

In [8]:
a.ndim #ndim - how many dimensions the array have.

1

In [9]:
a.shape # shape -size of ana rray

(5,)

In [10]:
len(a)

5

###**2D , 3D.... Arrays**

In [13]:
b=np.array([[1,2,3],[4,5,6]]) #listoflist we give
b

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
print(b.ndim)
print(b.shape) # 2 rows and 3 columns
print(len(b))  # size of 1st dimension i.e number of rows

2
(2, 3)
2


In [21]:
c=np.array([[[1,2,3],[4,5,6],[7,8,9],[10,11,12]]]) #listoflistoflist we give
c

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9],
        [10, 11, 12]]])

In [22]:
print(c.ndim)
print(c.shape)
#The first dimension is the outermost list (contains one element).
# The second dimension contains four rows (each of these rows is a list).
# The third dimension contains three elements in each of those rows.
print(len(c))  # size of 1st dimension i.e number of rows

3
(1, 4, 3)
1


* 1D Vector
* 2D matrix
* nD Tensor

##**Functions for creating arrays**

In [23]:
#using  arange Function
# arange -- array valued version of the built in python range function
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [24]:
b = np.arange(1,10,2) #start , end, step
b

array([1, 3, 5, 7, 9])

In [25]:
#using linspace -- linear space
a = np.linspace(0,1,6) #start, end, no of points
a
#no of points 6 is dividing 1 to 1 into 6 parts

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [26]:
#common arrays
a=np.ones((3,3)) #(3,3) is tuple
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [28]:
a=np.zeros((4,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

###**Identity Matrix**

In [29]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [31]:
np.eye(3,2)

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

###**Diagonal Matrix**

In [32]:
a = np.diag([1,2,3,4])
a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [33]:
np.diag(a)

array([1, 2, 3, 4])

###**using random**

In [35]:
a = np.random.rand(4) #random- module, rand- function
a
#uniform distributed random numbers

array([0.00452319, 0.97743604, 0.96081939, 0.78895177])

In [36]:
a = np.random.randn(4) #random- module, randn- rand normal function
a
#standard normal variable numbers

array([ 0.06251958, -0.0579229 , -1.76709557, -1.24126463])