<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/nditer.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
a = np.arange(12)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [7]:
a1=a.reshape(3,4)
print(a1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [12]:
#Iterating over a single array:
a1=a.reshape(3,4)
print(a1)

print()
for element in np.nditer(a1):
  print(element,end='')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

01234567891011

In [22]:
# Iterating over multiple arrays:
a1 = np.array([[1,2],[3,4]])
a2 = np .array([[1,1],[2,3]])

for a,b in np.nditer([a1,a2]):
  print(f"a1:{a},a2:{b}")
  # We're using f-strings to format the output, which makes it more readable.
# The nditer function allows us to easily iterate over multiple arrays at the same time, even if they have different shapes.

a1:1,a2:1
a1:2,a2:1
a1:3,a2:2
a1:4,a2:3
