<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/NumPy_Operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

In [ ]:
pip install numpy

In [1]:
import numpy as np


### Creating arrays

In [ ]:
arr = np.array([10,20,30,40])
print(arr)
print(type(arr))

[10 20 30 40]
<class 'numpy.ndarray'>


In [ ]:
 arr = np.array( [ [1,2,3],[4,5,6] ] )
 print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
zeroes = np.zeros((3,2))
print(zeroes)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [ ]:
one = np.ones((3,2))
print(one)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


 ### Array Properties- shape,size,dtype

In [ ]:
 arr = np.array( [ [1,2,3],[4,5,6] ] )
 print(arr)
 print(arr.shape) #no of rows and columns
 print(arr.size) #number of elements
 print(arr.ndim) #number dimensions
 print(len(arr)) #number of nested values
 print(type(arr)) #type of variable
 print(arr.dtype) #data type of variable
 print(arr.astype(float)) #conversion of data type

[[1 2 3]
 [4 5 6]]
(2, 3)
6
2
2
<class 'numpy.ndarray'>
int64
[[1. 2. 3.]
 [4. 5. 6.]]


### Reshape() and flatten()

In [ ]:
arr= np.arange(9)
print(arr)
newarr = arr.reshape(3,3)
newarr


[0 1 2 3 4 5 6 7 8]


array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.ndim)
flattenedarray = arr.flatten()
print(flattenedarray)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2
[1 2 3 4 5 6 7 8 9]


### INDEXING

In [ ]:
#for one dimension array
arr =  np.array([100,20,30,40,50,60])
print(arr[0])
print(arr[-2])
print(arr[[0,4,5]]) #if we want to access multiple index elements at once

100
50
[100  50  60]


In [ ]:
#for two dimension array
arr = np.array([[10,20,30],[40,50,60],[70,80,90]])
print(arr)
print(arr[1,2])
print(arr[-1,-2])

[[10 20 30]
 [40 50 60]
 [70 80 90]]
60
80


### Slicing

In [ ]:
#For 1Darray
arr =  np.array([100,20,30,40,50,60])
print(arr[1:3])
print(arr[1:])
print(arr[:3])
print(arr[0:4:1])
print(arr[0:4:2])
print(arr[0:4:3])
print(arr[::-1]) # reverse the array

[20 30]
[20 30 40 50 60]
[100  20  30]
[100  20  30  40]
[100  30]
[100  40]
[ 60  50  40  30  20 100]


In [ ]:
#For 2D array
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10,11,12]])
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:
arr1= arr[0:2,0:3]
print(arr1)

[[1 2 3]
 [5 6 7]]


In [ ]:
arr1= arr[0:1,0:1]
print(arr1)

[[1]]


In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10,11,12]])
arr1= arr[0,:]
# 0 selects the first row.
# : means all columns.
print(arr1)

[1 2 3 4]


In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10,11,12]])
arr1= arr[:,0]
#: means all rows.
#0 selects the 1st column (indexing starts from 0).
print(arr1)

[1 5 9]


In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10,11,12]])
arr1= arr[0:2,0:2]
# 0:2 selects the first two rows.
# 0:2 selects the first two columns.
print(arr1)

[[1 2]
 [5 6]]


In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10,11,12]])
arr1= arr[::2,::2]
# ::2 means select every second row/column.

print(arr1)

[[ 1  3]
 [ 9 11]]


### Modifying Subarrays

In [ ]:
arr = np.array([[1, 2, 3, 4],[5, 6, 7, 8],[9, 10,11,12]])
print(arr)
arr[0:2,0:2] = [[99,99],[100,100]]
# 0:2 selects the first two rows.
# 0:2 selects the first two columns.
print(arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 99  99   3   4]
 [100 100   7   8]
 [  9  10  11  12]]


### Mathematical Operations

In [ ]:
# a1 = np.array([[1,2,3],[4,5,6]])
# a2 = np.array([[7,8,9],[1,2,3]])
a1 = np.array([1,2,3,4,5,6])
a2 = np.array([7,8,9,1,2,3])
print(a1+a2)

[ 8 10 12  5  7  9]


In [ ]:
a1 = np.array([[1,2,3],[4,5,6]])
a2 = np.array([[7,8,9],[1,2,3]])
print(a1+a2)

[[ 8 10 12]
 [ 5  7  9]]


Mathematical Functions and operations

In [6]:
#1D array
arr = np.array([1,2,3,4])
print(arr+2)
print(arr -2)
print( arr*2)
print(arr/2)
print( arr **2)

[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[ 1  4  9 16]


In [11]:
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[4,5,6],[4,5,6]])
arr3 = np.array([4,9,16])
print(np.add(arr1,arr2))
print("________")
print(np.subtract(arr1,arr2))
print("________")
print(np.multiply(arr1,arr2))
print("________")
print(np.power(arr1,arr2))
print("________")
print(np.divide(arr1,arr2))
print("________")
print(np.sqrt(arr3))

[[5 7 9]
 [5 7 9]]
________
[[-3 -3 -3]
 [-3 -3 -3]]
________
[[ 4 10 18]
 [ 4 10 18]]
________
[[  1  32 729]
 [  1  32 729]]
________
[[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]]
________
[2. 3. 4.]


In [14]:
arr1 = np.array([[1,2,3],[1,2,3]])
arr2 = np.array([[4,5,6],[4,5,6]])
arr3 = np.array([4,9,16])
print(arr1+arr2)
print("________")
print(arr1- arr2)
print("________")
print(arr1*arr2)
print("________")
print(arr1/arr2)
print("________")
print(arr3**2)

[[5 7 9]
 [5 7 9]]
________
[[-3 -3 -3]
 [-3 -3 -3]]
________
[[ 4 10 18]
 [ 4 10 18]]
________
[[0.25 0.4  0.5 ]
 [0.25 0.4  0.5 ]]
________
[ 16  81 256]


### JOIN and SPLIT arrays

In [16]:
#concatenate
arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])
print(np.concatenate([arr1,arr2]))

[1 2 3 4 5 6]
