<a href="https://colab.research.google.com/github/KVenkataPavani/NumPy-Numerical_Python/blob/main/Sort_Search_Filter.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([2,0,5,8,1])
print(np.sort(a))

[0 1 2 5 8]


In [3]:
a = np.array([[2,0,5,8,1],[3,7,2,8,0]])
print(np.sort(a))

[[0 1 2 5 8]
 [0 2 3 7 8]]


In [7]:
#Where = search
a = np.array([2,0,5,8,1])
a1= np.where(a==8)
print(a1)

(array([3]),)


In [8]:
#Where = search
a = np.array([2,0,5,8,1])
a1= np.where(a%2==0)
print(a1)

(array([0, 1, 3]),)


In [10]:
#Search Sorted
#Where = search
a = np.array([1,2,3,4,5,6]) #in search sortd array has to be sorted
a1= np.searchsorted(a,2)
print(a1)

1


In [13]:
#Filter

a = np.array([1,2,3,4])
a1 = [True ,False,True, False] #watever values we want we write it true
a2 = a[a1]
print(a2)


[1 3]


In [14]:
#Filter

a = np.array([1,2,3,4])
a1 = a>2
a2 = a[a1]
print(a2)


[3 4]


In [19]:
#Filter

a = np.array([1,2,3,4])
a1 = a%2==0
a2 = a[a1]
print(a2)


[2 4]
